### ISSUE TITLE
The decision of suicide for the win.

### ISSUE THREAD

**Issue by dok441** [TTT-2/ttt2-role_shini#10]
I have often noticed that Shinigami often kills himself by writing kill in the console or jumping off the roof and deliberately wants to become Shinigami in order to kill traitors and I have a question whether it is normal to do so with the role?! Can make the conditions he needs to become shinigs, you have to die of a hostile role, and only then.

**Comment by TimGoll** [comment]
But the shini doesn't know that they are a shini. Why would they do this? They could be a normal innocent as well

**Comment by saibotk** [comment]
I wouldn't want that, as the role is not that strong and also it is quite risky to give up as an innocent, because you dont know, that you are a Shinigami for 100%. So i don't think this should be limited.
I'm closing this, as this is not what I want the role to be, but thank you for your suggestion!

**Comment by TimGoll** [comment]
@saibotk What about not being revived if you kill yourself? So you're only revived by a player or world kill.

**Comment by saibotk** [comment]
No, i want them to have a chance, even if they eg. fall from a roof.
