### ISSUE TITLE
Getting errors when using with spectator deathmatch

### ISSUE THREAD

**Issue by tobi-nb** [TTT-2/ttt2-role_shini#18]
When a shinigami dies twice and goes into the spectator deathmatch [(addon in the workshop)](https://steamcommunity.com/sharedfiles/filedetails/?id=1997666028), the following error gets printed the whole time while he's alive in the spectator deathmatch:

```
[[TTT2] Shinigami [ROLE]] lua/terrortown/entities/roles/shinigami/shared.lua:153: attempt to index local 'noLag' (a nil value)
  1. fn - lua/terrortown/entities/roles/shinigami/shared.lua:153
   2. Run - lua/ulib/shared/hook.lua:109
    3. fn - lua/sh_spectator_deathmatch.lua:75
     4. unknown - lua/ulib/shared/hook.lua:109 
   ```

Here's my [workshop collection](https://steamcommunity.com/sharedfiles/filedetails/?id=849222406) if you need more information.

**Comment by saibotk** [comment]
Hey,
Thanks for the report, but this seems to be caused by the SpecDM addon itself, as it does not pass valid data to the hook. 
The issue is in line https://github.com/TheNickSkater/TTT_Spectator_Deathmatch/blob/7646bc1ccc75b8d0c4c78989252c54c9b830a5db/lua/sh_spectator_deathmatch.lua#L75

You should open up an issue in their repository https://github.com/TheNickSkater/TTT_Spectator_Deathmatch 

CC: @TheNickSkater
